# Generated by Django 5.1.2 on 2024-10-22 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('author', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2024, 10, 22, 20, 0, 52, 368650, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
