# Generated by Django 5.1.2 on 2024-10-22 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=200)),
                ('firstname', models.TextField(max_length=75)),
                ('lastname', models.TextField(max_length=75)),
                ('email', models.TextField(max_length=200)),
                ('password', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 22, 21, 41, 10, 954787, tzinfo=datetime.timezone.utc)),
        ),
    ]
