# Generated by Django 5.1.2 on 2024-10-23 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_customer_email_alter_customer_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 18, 19, 10, 981557, tzinfo=datetime.timezone.utc)),
        ),
    ]
