# Generated by Django 5.1.2 on 2024-10-23 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 20, 41, 13, 413424, tzinfo=datetime.timezone.utc)),
        ),
    ]
